name: youtube-automation-tools

services:
  transcribe-service:
    build: ./services/transcribe_service
    image: ghcr.io/joshyorko/transcribe_service:latest
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    runtime: nvidia
  
    container_name: transcribe-service
    ports:
      - "8000:8000"
    volumes:
      - ./services/transcribe_service:/app
    environment:
      - SERVICE_ENV="development"
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    networks:
      - app_network
    restart: always
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--reload", "--port", "8000"]



  thumbnail-creation-service:
    build: ./services/thumbnail_creation_service
    image: ghcr.io/joshyorko/thumbnail_creation_service:latest
    container_name: thumbnail-creation-service
    ports:
      - "8001:8001"
    volumes:
      - ./services/thumbnail_creation_service:/app
    environment:
      - SERVICE_ENV="development"
    networks:
      - app_network
    restart: always
    env_file:
      - ./.env
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8001", "--reload"]

  ci-cd-pipeline:
    image: ghcr.io/joshyorko/ci_cd_pipeline:latest
    container_name: ci-cd-pipeline
    build:
      context: .
      dockerfile: ./ci_cd/Dockerfile
    environment:
      - CI=true
    networks:
      - app_network
    restart: always
    command: ["./ci_cd/run_pipeline.sh"]

  gitops-deployment:
    image: ghcr.io/joshyorko/gitops_deployment:latest
    container_name: gitops-deployment
    build:
      context: .
      dockerfile: ./gitops/Dockerfile
    environment:
      - GITOPS=true
    networks:
      - app_network
    restart: always
    command: ["./gitops/deploy.sh"]

networks:
  app_network:
    driver: bridge

volumes:
  app_data:
    driver: local
