name: youtube-automation-tools

services:
  transcribe-service:
    build: ./services/transcribe_service
    image: ghcr.io/joshyorko/transcribe_service:latest
    container_name: transcribe-service
    ports:
      - "8000:8000"
    volumes:
      - ./services/transcribe_service:/app
    environment:
      - SERVICE_ENV="development"
    networks:
      - app_network
    restart: always
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--reload", "--port", "8000"]
    # CPU is default configuration
    # GPU configuration is applied when using the 'gpu' profile

  transcribe-service-gpu:
    profiles:
      - gpu
    extends:
      service: transcribe-service
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    runtime: nvidia
    environment:
      - SERVICE_ENV="development"
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility

  thumbnail-creation-service:
    build: ./services/thumbnail_creation_service
    image: ghcr.io/joshyorko/thumbnail_creation_service:latest
    container_name: thumbnail-creation-service
    ports:
      - "8001:8001"
    volumes:
      - ./services/thumbnail_creation_service:/app
    environment:
      - SERVICE_ENV="development"
    networks:
      - app_network
    restart: always
    env_file:
      - ./.env
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8001", "--reload"]

networks:
  app_network:
    driver: bridge

volumes:
  app_data:
    driver: local