name: transcribe-service

services:
  transcribe-service:
    build: ./youtube-automation-tools/services/transcribe_service
    image:  ghcr.io/joshyorko/transcribe-service:latest
    container_name: transcribe-service
    ports:
      - "8000:8000"
    environment:
      - SERVICE_ENV="PRODUCTION"
    networks:
      - app_network
    restart: always
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]



networks:
  app_network:
    driver: bridge

volumes:
  app_data:
    driver: local