name: transcribe-service

services:
  transcribe-service:
    build: ./youtube-automation-tools/services/transcribe_service
    image:  ghcr.io/joshyorko/transcribe-service:latest
    container_name: transcribe-service

    environment:
      - SERVICE_ENV="PRODUCTION"
    networks:
      - app_network
    restart: always
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8007"]



networks:
  app_network:
    driver: bridge

volumes:
  app_data:
    driver: local
